/*

	TVP2 ( T Visual Presenter 2 )  A script authoring tool
	Copyright (C) 2000-2009 W.Dee <dee@kikyou.info> and contributors

	See details of license at "license.txt"


*/
/* core C routines for graphics operations */
/* this file is always generated by gengl.pl rev. 0.1 */


#ifndef __TVPGL_X86_INTF__
#define __TVPGL_X86_INTF__

#include "tjsTypes.h"
#include "gl/tvpgl.h"

#endif